name: fl_rt_embedder
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  common:
    path: ../common
  ffi:
  fl_rt_bindings:
    path: ../bindings
  glfw_dart:
    git:
      url: https://github.com/jld3103/glfw_dart
  path:

dependency_overrides:
  ffi: '>=1.0.0' # Force override, because glfw_dart uses an old version